/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desk_drink;

import desk_food.*;

/**
 *
 * @author muham
 */
public class ice_cream extends javax.swing.JPanel {

    /**
     * Creates new form cinnamon
     */
    public ice_cream() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        qty_croffle2 = new javax.swing.JLabel();
        qty_croffle3 = new javax.swing.JLabel();
        qty_croffle4 = new javax.swing.JLabel();
        qty_croffle6 = new javax.swing.JLabel();
        qty_croffle7 = new javax.swing.JLabel();
        qty_croffle8 = new javax.swing.JLabel();
        qty_croffle9 = new javax.swing.JLabel();
        qty_croffle10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(480, 460));
        setMinimumSize(new java.awt.Dimension(480, 460));
        setPreferredSize(new java.awt.Dimension(480, 460));
        setLayout(new java.awt.CardLayout());

        bg.setBackground(new java.awt.Color(0, 0, 0));
        bg.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        bg.setMaximumSize(new java.awt.Dimension(480, 460));
        bg.setMinimumSize(new java.awt.Dimension(480, 460));
        bg.setPreferredSize(new java.awt.Dimension(480, 460));
        bg.setLayout(null);

        qty_croffle2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        qty_croffle2.setForeground(new java.awt.Color(218, 165, 32));
        qty_croffle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qty_croffle2.setText("ICE CREAM");
        qty_croffle2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        bg.add(qty_croffle2);
        qty_croffle2.setBounds(0, 40, 480, 40);

        qty_croffle3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        qty_croffle3.setForeground(new java.awt.Color(218, 165, 32));
        qty_croffle3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qty_croffle3.setText("seluruh dunia, terkenal karena teksturnya yang lembut dan");
        bg.add(qty_croffle3);
        qty_croffle3.setBounds(0, 270, 480, 19);

        qty_croffle4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        qty_croffle4.setForeground(new java.awt.Color(218, 165, 32));
        qty_croffle4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qty_croffle4.setText("rasa yang beragam. Terbuat dari campuran susu, krim, gula,");
        bg.add(qty_croffle4);
        qty_croffle4.setBounds(0, 290, 480, 19);

        qty_croffle6.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        qty_croffle6.setForeground(new java.awt.Color(218, 165, 32));
        qty_croffle6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qty_croffle6.setText("Ice cream adalah salah satu dessert yang paling populer di");
        bg.add(qty_croffle6);
        qty_croffle6.setBounds(0, 250, 480, 20);

        qty_croffle7.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        qty_croffle7.setForeground(new java.awt.Color(218, 165, 32));
        qty_croffle7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qty_croffle7.setText("dan berbagai bahan tambahan seperti buah-buahan, cokelat,");
        bg.add(qty_croffle7);
        qty_croffle7.setBounds(0, 310, 490, 19);

        qty_croffle8.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        qty_croffle8.setForeground(new java.awt.Color(218, 165, 32));
        qty_croffle8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qty_croffle8.setText("memuaskan.");
        bg.add(qty_croffle8);
        qty_croffle8.setBounds(0, 370, 480, 19);

        qty_croffle9.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        qty_croffle9.setForeground(new java.awt.Color(218, 165, 32));
        qty_croffle9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qty_croffle9.setText("kacang-kacangan, atau rempah-rempah, ice cream");
        bg.add(qty_croffle9);
        qty_croffle9.setBounds(0, 330, 480, 19);

        qty_croffle10.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        qty_croffle10.setForeground(new java.awt.Color(218, 165, 32));
        qty_croffle10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qty_croffle10.setText("menawarkan kenikmatan yang menyegarkan dan");
        bg.add(qty_croffle10);
        qty_croffle10.setBounds(0, 350, 480, 19);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_desk_drink/ice cream desk.png"))); // NOI18N
        bg.add(jLabel1);
        jLabel1.setBounds(130, 90, 270, 160);

        add(bg, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel qty_croffle10;
    private javax.swing.JLabel qty_croffle2;
    private javax.swing.JLabel qty_croffle3;
    private javax.swing.JLabel qty_croffle4;
    private javax.swing.JLabel qty_croffle6;
    private javax.swing.JLabel qty_croffle7;
    private javax.swing.JLabel qty_croffle8;
    private javax.swing.JLabel qty_croffle9;
    // End of variables declaration//GEN-END:variables
}
