/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desk_food;

/**
 *
 * @author muham
 */
public class lasagna extends javax.swing.JPanel {

    /**
     * Creates new form cinnamon
     */
    public lasagna() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        qty_croffle2 = new javax.swing.JLabel();
        qty_croffle3 = new javax.swing.JLabel();
        qty_croffle4 = new javax.swing.JLabel();
        qty_croffle5 = new javax.swing.JLabel();
        qty_croffle6 = new javax.swing.JLabel();
        qty_croffle7 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        bg.setBackground(new java.awt.Color(0, 0, 0));
        bg.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        bg.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_desc_food/lasagna desk.png"))); // NOI18N
        bg.add(jLabel1);
        jLabel1.setBounds(130, 90, 230, 180);

        qty_croffle2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        qty_croffle2.setForeground(new java.awt.Color(218, 165, 32));
        qty_croffle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qty_croffle2.setText("LASAGNA");
        qty_croffle2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        bg.add(qty_croffle2);
        qty_croffle2.setBounds(0, 40, 480, 40);

        qty_croffle3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        qty_croffle3.setForeground(new java.awt.Color(218, 165, 32));
        qty_croffle3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qty_croffle3.setText("paling terkenal dari Italia. Dikenal karena lapisan pasta yang");
        bg.add(qty_croffle3);
        qty_croffle3.setBounds(0, 300, 480, 19);

        qty_croffle4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        qty_croffle4.setForeground(new java.awt.Color(218, 165, 32));
        qty_croffle4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qty_croffle4.setText("lembut, saus daging yang kaya, keju yang meleleh, dan saus");
        bg.add(qty_croffle4);
        qty_croffle4.setBounds(0, 320, 480, 19);

        qty_croffle5.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        qty_croffle5.setForeground(new java.awt.Color(218, 165, 32));
        qty_croffle5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qty_croffle5.setText("dan tekstur yang memuaskan.");
        bg.add(qty_croffle5);
        qty_croffle5.setBounds(0, 360, 480, 19);

        qty_croffle6.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        qty_croffle6.setForeground(new java.awt.Color(218, 165, 32));
        qty_croffle6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qty_croffle6.setText("Lasagna adalah salah satu hidangan pasta panggang yang");
        bg.add(qty_croffle6);
        qty_croffle6.setBounds(0, 280, 480, 20);

        qty_croffle7.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        qty_croffle7.setForeground(new java.awt.Color(218, 165, 32));
        qty_croffle7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qty_croffle7.setText("béchamel yang creamy, lasagna menawarkan perpaduan rasa");
        bg.add(qty_croffle7);
        qty_croffle7.setBounds(0, 340, 480, 19);

        add(bg, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel qty_croffle2;
    private javax.swing.JLabel qty_croffle3;
    private javax.swing.JLabel qty_croffle4;
    private javax.swing.JLabel qty_croffle5;
    private javax.swing.JLabel qty_croffle6;
    private javax.swing.JLabel qty_croffle7;
    // End of variables declaration//GEN-END:variables
}
