/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author muham
 */
public class contact extends javax.swing.JPanel {

    /**
     * Creates new form contact
     */
    public contact() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dsr = new javax.swing.JPanel();
        bg = new javax.swing.JPanel();
        pn_atas = new javax.swing.JLabel();
        WhatsApp = new javax.swing.JLabel();
        Twitter = new javax.swing.JLabel();
        Instagram = new javax.swing.JLabel();
        no_wa = new javax.swing.JLabel();
        acc_twitter = new javax.swing.JLabel();
        acc_ig = new javax.swing.JLabel();
        gif = new javax.swing.JLabel();

        dsr.setLayout(new java.awt.CardLayout());

        bg.setBackground(new java.awt.Color(0, 0, 0));
        bg.setLayout(null);

        pn_atas.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        pn_atas.setForeground(new java.awt.Color(218, 165, 32));
        pn_atas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pn_atas.setText("CONTACT US");
        pn_atas.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        bg.add(pn_atas);
        pn_atas.setBounds(20, 20, 1200, 28);

        WhatsApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WhatsApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_contact/whatapp.png"))); // NOI18N
        bg.add(WhatsApp);
        WhatsApp.setBounds(72, 110, 100, 100);

        Twitter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Twitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_contact/twitter.png"))); // NOI18N
        bg.add(Twitter);
        Twitter.setBounds(72, 260, 100, 100);

        Instagram.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Instagram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_contact/ig.png"))); // NOI18N
        bg.add(Instagram);
        Instagram.setBounds(72, 410, 100, 100);

        no_wa.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        no_wa.setForeground(new java.awt.Color(255, 255, 255));
        no_wa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        no_wa.setText("+62 858-8820-2616");
        bg.add(no_wa);
        no_wa.setBounds(210, 150, 160, 20);

        acc_twitter.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        acc_twitter.setForeground(new java.awt.Color(255, 255, 255));
        acc_twitter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_twitter.setText("@mobicafe0__o");
        bg.add(acc_twitter);
        acc_twitter.setBounds(210, 300, 160, 20);

        acc_ig.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        acc_ig.setForeground(new java.awt.Color(255, 255, 255));
        acc_ig.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_ig.setText("@mobicafe0__o");
        bg.add(acc_ig);
        acc_ig.setBounds(210, 450, 160, 20);

        gif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gif/download_1.gif"))); // NOI18N
        gif.setText("jLabel8");
        bg.add(gif);
        gif.setBounds(550, 170, 500, 280);

        dsr.add(bg, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dsr, javax.swing.GroupLayout.DEFAULT_SIZE, 1292, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dsr, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Instagram;
    private javax.swing.JLabel Twitter;
    private javax.swing.JLabel WhatsApp;
    private javax.swing.JLabel acc_ig;
    private javax.swing.JLabel acc_twitter;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel dsr;
    private javax.swing.JLabel gif;
    private javax.swing.JLabel no_wa;
    private javax.swing.JLabel pn_atas;
    // End of variables declaration//GEN-END:variables
}
