/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author muham
 */
public class home extends javax.swing.JPanel {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dasar = new javax.swing.JPanel();
        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelGradient1 = new JPanelGradient.JPanelGradient();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanelGradient2 = new JPanelGradient.JPanelGradient();
        jPanelGradient3 = new JPanelGradient.JPanelGradient();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1200, 670));
        setMinimumSize(new java.awt.Dimension(1200, 670));
        setPreferredSize(new java.awt.Dimension(1200, 670));

        dasar.setLayout(new java.awt.CardLayout());

        bg.setBackground(new java.awt.Color(0, 0, 0));
        bg.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(218, 165, 32)));
        bg.setMaximumSize(new java.awt.Dimension(1200, 670));
        bg.setMinimumSize(new java.awt.Dimension(1200, 670));
        bg.setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_home/Logo.png"))); // NOI18N
        bg.add(jLabel1);
        jLabel1.setBounds(510, 140, 170, 170);

        javax.swing.GroupLayout jPanelGradient1Layout = new javax.swing.GroupLayout(jPanelGradient1);
        jPanelGradient1.setLayout(jPanelGradient1Layout);
        jPanelGradient1Layout.setHorizontalGroup(
            jPanelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanelGradient1Layout.setVerticalGroup(
            jPanelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        bg.add(jPanelGradient1);
        jPanelGradient1.setBounds(590, 340, 5, 100);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(218, 165, 32));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Temukan tempat di mana kenyamanan dan cita rasa berkumpul di Mobi Cafe. Terletak di pusat kota,");
        bg.add(jLabel2);
        jLabel2.setBounds(320, 490, 550, 15);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(218, 165, 32));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(" Mobi Cafe menawarkan pengalaman bersantai yang tak tertandingi dalam suasana modern dan elegan.");
        bg.add(jLabel3);
        jLabel3.setBounds(320, 510, 550, 15);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(218, 165, 32));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Desain interior kami yang minimalis dengan sentuhan kayu hangat dan aksen metalik menciptakan lingkungan");
        bg.add(jLabel4);
        jLabel4.setBounds(300, 530, 600, 15);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(218, 165, 32));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText(" yang sempurna untuk bekerja, belajar, atau sekadar menikmati waktu bersama teman.");
        bg.add(jLabel5);
        jLabel5.setBounds(300, 550, 600, 15);

        jPanelGradient2.setColorEnd(new java.awt.Color(0, 0, 0));
        jPanelGradient2.setColorStart(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelGradient2Layout = new javax.swing.GroupLayout(jPanelGradient2);
        jPanelGradient2.setLayout(jPanelGradient2Layout);
        jPanelGradient2Layout.setHorizontalGroup(
            jPanelGradient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelGradient2Layout.setVerticalGroup(
            jPanelGradient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        bg.add(jPanelGradient2);
        jPanelGradient2.setBounds(400, 220, 100, 5);

        javax.swing.GroupLayout jPanelGradient3Layout = new javax.swing.GroupLayout(jPanelGradient3);
        jPanelGradient3.setLayout(jPanelGradient3Layout);
        jPanelGradient3Layout.setHorizontalGroup(
            jPanelGradient3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelGradient3Layout.setVerticalGroup(
            jPanelGradient3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        bg.add(jPanelGradient3);
        jPanelGradient3.setBounds(700, 220, 100, 5);

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("HIDANGAN LEZAT UNTUK SEGALA MOMEN");
        bg.add(jLabel6);
        jLabel6.setBounds(20, 140, 360, 19);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(218, 165, 32));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText(" dengan kualitas tinggi yang menyegarkan. Barista yang terampil siap");
        bg.add(jLabel9);
        jLabel9.setBounds(810, 200, 380, 15);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(218, 165, 32));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("membuatkan minuman favorit Anda, mulai dari milkshake hingga");
        bg.add(jLabel10);
        jLabel10.setBounds(810, 220, 380, 15);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(218, 165, 32));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("latte art yang indah. ");
        bg.add(jLabel11);
        jLabel11.setBounds(810, 240, 380, 15);

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("SELAMAT DATANG");
        bg.add(jLabel12);
        jLabel12.setBounds(520, 450, 150, 19);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(218, 165, 32));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Di Mobi Cafe, kami bangga menyajikan berbagai minuman");
        bg.add(jLabel13);
        jLabel13.setBounds(810, 180, 380, 15);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(218, 165, 32));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Hidangan yang dibuat dengan rasa cinta menghasilkan rasa yang nikmat");
        bg.add(jLabel14);
        jLabel14.setBounds(10, 210, 390, 15);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(218, 165, 32));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText(" di mulut. Nikmati hidangan ringan maupun berat yang menggugah selera.");
        bg.add(jLabel15);
        jLabel15.setBounds(10, 230, 400, 15);

        jLabel17.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("NIKMATI KOPI TERBAIK");
        bg.add(jLabel17);
        jLabel17.setBounds(820, 140, 360, 19);

        dasar.add(bg, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dasar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dasar, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel dasar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private JPanelGradient.JPanelGradient jPanelGradient1;
    private JPanelGradient.JPanelGradient jPanelGradient2;
    private JPanelGradient.JPanelGradient jPanelGradient3;
    // End of variables declaration//GEN-END:variables
}
