/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import view.home;
import java.awt.Color;
import view.order;
import view.contact;

/**
 *
 * @author muham
 */
public class main extends javax.swing.JFrame {
            
    public main() {
        initComponents();
        gradient_kanan_judul.setBackground(new Color (0,0,0,1));
        gradient_kiri_judul.setBackground(new Color (0,0,0,1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pn_atas = new javax.swing.JPanel();
        pn_toko = new javax.swing.JPanel();
        toko = new javax.swing.JLabel();
        gradient_kiri_judul = new JPanelGradient.JPanelGradient();
        jPanel2 = new javax.swing.JPanel();
        gradient_kanan_judul = new JPanelGradient.JPanelGradient();
        pn_dasar = new javax.swing.JPanel();
        pn_order = new javax.swing.JPanel();
        order = new javax.swing.JLabel();
        gradient_kiri = new JPanelGradient.JPanelGradient();
        pn_home = new javax.swing.JPanel();
        home = new javax.swing.JLabel();
        gradient_kanan = new JPanelGradient.JPanelGradient();
        pn_contact = new javax.swing.JPanel();
        contact = new javax.swing.JLabel();
        pn_utama = new javax.swing.JPanel();
        home1 = new view.home();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1200, 800));
        setMinimumSize(new java.awt.Dimension(1200, 800));
        setUndecorated(true);
        setResizable(false);

        pn_toko.setBackground(new java.awt.Color(0, 0, 0));

        toko.setForeground(new java.awt.Color(255, 255, 255));
        toko.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        toko.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_home/Nama_Cafe_Load.png"))); // NOI18N

        javax.swing.GroupLayout gradient_kiri_judulLayout = new javax.swing.GroupLayout(gradient_kiri_judul);
        gradient_kiri_judul.setLayout(gradient_kiri_judulLayout);
        gradient_kiri_judulLayout.setHorizontalGroup(
            gradient_kiri_judulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 221, Short.MAX_VALUE)
        );
        gradient_kiri_judulLayout.setVerticalGroup(
            gradient_kiri_judulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        gradient_kanan_judul.setColorEnd(new java.awt.Color(0, 0, 0));
        gradient_kanan_judul.setColorStart(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout gradient_kanan_judulLayout = new javax.swing.GroupLayout(gradient_kanan_judul);
        gradient_kanan_judul.setLayout(gradient_kanan_judulLayout);
        gradient_kanan_judulLayout.setHorizontalGroup(
            gradient_kanan_judulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 221, Short.MAX_VALUE)
        );
        gradient_kanan_judulLayout.setVerticalGroup(
            gradient_kanan_judulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pn_tokoLayout = new javax.swing.GroupLayout(pn_toko);
        pn_toko.setLayout(pn_tokoLayout);
        pn_tokoLayout.setHorizontalGroup(
            pn_tokoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_tokoLayout.createSequentialGroup()
                .addContainerGap(347, Short.MAX_VALUE)
                .addComponent(toko)
                .addGap(343, 343, 343)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pn_tokoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_tokoLayout.createSequentialGroup()
                    .addGap(353, 353, 353)
                    .addComponent(gradient_kiri_judul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(626, Short.MAX_VALUE)))
            .addGroup(pn_tokoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_tokoLayout.createSequentialGroup()
                    .addGap(573, 573, 573)
                    .addComponent(gradient_kanan_judul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(406, Short.MAX_VALUE)))
        );
        pn_tokoLayout.setVerticalGroup(
            pn_tokoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toko, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addGroup(pn_tokoLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pn_tokoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_tokoLayout.createSequentialGroup()
                    .addContainerGap(25, Short.MAX_VALUE)
                    .addComponent(gradient_kiri_judul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(28, 28, 28)))
            .addGroup(pn_tokoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pn_tokoLayout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(gradient_kanan_judul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(28, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout pn_atasLayout = new javax.swing.GroupLayout(pn_atas);
        pn_atas.setLayout(pn_atasLayout);
        pn_atasLayout.setHorizontalGroup(
            pn_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_toko, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pn_atasLayout.setVerticalGroup(
            pn_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_atasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pn_toko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pn_atas, java.awt.BorderLayout.PAGE_START);

        pn_dasar.setBackground(new java.awt.Color(0, 0, 0));
        pn_dasar.setLayout(null);

        pn_order.setMaximumSize(new java.awt.Dimension(100, 30));
        pn_order.setMinimumSize(new java.awt.Dimension(100, 30));

        order.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        order.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        order.setText("ORDER");
        order.setMaximumSize(new java.awt.Dimension(30, 14));
        order.setMinimumSize(new java.awt.Dimension(30, 14));
        order.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pn_orderLayout = new javax.swing.GroupLayout(pn_order);
        pn_order.setLayout(pn_orderLayout);
        pn_orderLayout.setHorizontalGroup(
            pn_orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_orderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(order, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_orderLayout.setVerticalGroup(
            pn_orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(order, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        pn_dasar.add(pn_order);
        pn_order.setBounds(510, 0, 140, 30);

        gradient_kiri.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(218, 165, 32)));
        gradient_kiri.setLayout(null);

        pn_home.setBackground(new java.awt.Color(0, 0, 0));
        pn_home.setMaximumSize(new java.awt.Dimension(100, 30));
        pn_home.setMinimumSize(new java.awt.Dimension(100, 30));

        home.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home.setText("HOME");
        home.setMaximumSize(new java.awt.Dimension(30, 14));
        home.setMinimumSize(new java.awt.Dimension(30, 14));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pn_homeLayout = new javax.swing.GroupLayout(pn_home);
        pn_home.setLayout(pn_homeLayout);
        pn_homeLayout.setHorizontalGroup(
            pn_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_homeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_homeLayout.setVerticalGroup(
            pn_homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        gradient_kiri.add(pn_home);
        pn_home.setBounds(280, 1, 100, 30);

        pn_dasar.add(gradient_kiri);
        gradient_kiri.setBounds(0, 0, 600, 30);

        gradient_kanan.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(218, 165, 32)));
        gradient_kanan.setColorEnd(new java.awt.Color(0, 0, 0));
        gradient_kanan.setColorStart(new java.awt.Color(255, 255, 255));
        gradient_kanan.setLayout(null);

        pn_contact.setMaximumSize(new java.awt.Dimension(100, 30));
        pn_contact.setMinimumSize(new java.awt.Dimension(100, 30));

        contact.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        contact.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contact.setText("CONTACT");
        contact.setMaximumSize(new java.awt.Dimension(30, 14));
        contact.setMinimumSize(new java.awt.Dimension(30, 14));
        contact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pn_contactLayout = new javax.swing.GroupLayout(pn_contact);
        pn_contact.setLayout(pn_contactLayout);
        pn_contactLayout.setHorizontalGroup(
            pn_contactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_contactLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contact, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_contactLayout.setVerticalGroup(
            pn_contactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contact, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        gradient_kanan.add(pn_contact);
        pn_contact.setBounds(225, 1, 100, 30);

        pn_dasar.add(gradient_kanan);
        gradient_kanan.setBounds(600, 0, 600, 30);

        pn_utama.setBackground(new java.awt.Color(0, 0, 0));
        pn_utama.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(218, 165, 32)));
        pn_utama.setMaximumSize(new java.awt.Dimension(1200, 670));
        pn_utama.setMinimumSize(new java.awt.Dimension(1200, 670));
        pn_utama.setLayout(new java.awt.BorderLayout());
        pn_utama.add(home1, java.awt.BorderLayout.CENTER);

        pn_dasar.add(pn_utama);
        pn_utama.setBounds(0, 30, 1200, 670);

        getContentPane().add(pn_dasar, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        pn_utama.removeAll();
        pn_utama.add(new home());
        pn_utama.repaint();
        pn_utama.revalidate();
        
        pn_home.setBackground(Color.BLACK);
        home.setForeground(Color.WHITE);
        pn_order.setBackground(Color.WHITE);
        order.setForeground(Color.BLACK);
        pn_contact.setBackground(Color.WHITE);
        contact.setForeground(Color.BLACK);
    }//GEN-LAST:event_homeMouseClicked

    private void orderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderMouseClicked
        pn_utama.removeAll();
        pn_utama.add(new order());
        pn_utama.repaint();
        pn_utama.revalidate();
        
        pn_home.setBackground(Color.WHITE);
        home.setForeground(Color.BLACK);
        pn_order.setBackground(Color.BLACK);
        order.setForeground(Color.WHITE);
        pn_contact.setBackground(Color.WHITE);
        contact.setForeground(Color.BLACK);
    }//GEN-LAST:event_orderMouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        dispose();
    }//GEN-LAST:event_jPanel2MouseClicked

    private void contactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactMouseClicked
        pn_utama.removeAll();
        pn_utama.add(new contact());
        pn_utama.repaint();
        pn_utama.revalidate();
        
        pn_home.setBackground(Color.WHITE);
        home.setForeground(Color.BLACK);
        pn_order.setBackground(Color.WHITE);
        order.setForeground(Color.BLACK);
        pn_contact.setBackground(Color.BLACK);
        contact.setForeground(Color.WHITE);
    }//GEN-LAST:event_contactMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contact;
    private JPanelGradient.JPanelGradient gradient_kanan;
    private JPanelGradient.JPanelGradient gradient_kanan_judul;
    private JPanelGradient.JPanelGradient gradient_kiri;
    private JPanelGradient.JPanelGradient gradient_kiri_judul;
    private javax.swing.JLabel home;
    private view.home home1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel order;
    private javax.swing.JPanel pn_atas;
    private javax.swing.JPanel pn_contact;
    private javax.swing.JPanel pn_dasar;
    private javax.swing.JPanel pn_home;
    private javax.swing.JPanel pn_order;
    private javax.swing.JPanel pn_toko;
    private javax.swing.JPanel pn_utama;
    private javax.swing.JLabel toko;
    // End of variables declaration//GEN-END:variables
}
